# -*- coding: utf-8 -*-
"""tic tac toe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ie2_kzSxmxnzRjmTqEU-6PR_wXQiTmTg

# Capstone Project: AI agent for Tic-Tac-Toe Game

---

### Context

We often come in a situation where we have to evaluate our performance with respect to other participants. This is mostly the case when we are competing in the games or competition. In the case of algorithmic strategy, this is true. To solve a problem there may be more than one solution. To choose one we have to make a comparison between them. We have to make a quantitative analysis of our algorithm or strategy and then chose one. Games give the best platform for this in Artificial Intelligence as we have points to calculate our performance.

---

### Problem Statement

In this project, you have to program a simple AI agent that could beat random strategy in the game of **Tic-Tac-Toe**. Tic-Tac-Toe is a widely played game all over the world. Tic-Tac-Toe is a two-player game that is played on a 3 by 3 grid. Each player takes a turn in marking $X$ and $O$.  The player who succeeds in placing three of their marks in a diagonal, horizontal, or vertical row is the winner.

Below is the link on how to play tic-tac-toe:

[How to Play Tic-Tac-Toe](https://www.wikihow.com/Play-Tic-Tac-Toe)

**Player Input Format:**

A player should play his/her move by entering the numbers 1 or 2 where:

- $1$ denotes $X$.

- $2$ denotes $O$.

---

### Things To Do

1. Create the `empty_positions()` Function.

2. Create the `evaluate()` Function.

3. Play with random strategy for both players.

4. Play with random strategy for player2 and AI bot strategy for player1.

---

### Strategy

**Random Strategy:**

As the name suggests random strategy is just marking at any random square in the $3 \times 3$ grid. A player first looks out for all possible squares where he can mark $X$ or $O$ as mutually decided by the players.

Example:

Player 2 move: 2 2

Player 1 move: 2 1

Player 2 move: 1 0

Player 1 move: 0 0

Player 2 move: 0 2

Player 1 move: 1 1

Player 2 move: 0 1

Player 1 move: 1 2

Player 2 move: 2 0

In above game we can observe that there is no specific strategy by any player. They are just selecting any random square. Even if some moves increase their chance of winning, as can be observed by us.

**AI Bot:**

We come up with an algorithm where the player will mark at the center square if it is empty. This will always be the case if he is having the first attempt. If the player is having a second attempt, this will be the case when another player has not marked the center square.

Player 1 move: 1 1

Player 2 move: 0 0

Player 1 move: 2 0

Player 2 move: 0 1

Player 1 move: 2 1

Player 2 move: 1 2

Player 1 move: 2 2

Player 1 wins

In above game we can observe that marking at center square increase the chances of AI bot to win the game.

**Q:** Can you think of any other such strategy (Algorithm) for AI bot?

**A:**

---

### Gameplay

In this project, you have to play Tic-Tac-Toe $100$ times. Each player will get a chance to play the first move if he/she loses. Each game can end with either of the following three outcomes:
- Player1 wins: Player1 will get three of his marks ($1$) in a diagonal, horizontal, or vertical row.
- Player2 wins: Player2 will get three of his marks ($2$) in a diagonal, horizontal, or vertical row.
- Draw: Neither of the players can get three of their marks in a diagonal, horizontal, or vertical row till all squares are marked.

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/19UnY1KY19BAYLF3PDEAED37MoRitcX8Z?usp=sharing

2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_CapstoneProject1** format.

3. Now, write your code in the prescribed code cells.

---

### Game Requirements

To make this game, you have to create:

- A $3\times3$  `tic_tac_toe` 2D list.

- 1D list `positions` to return the list of empty positions.

- `empty_positions()` function to check for all empty positions.

- `evaluate()` function to check whether the game has reached any conclusion or not.

- `player1_wins`, `player2_wins`, and `draw` variables to keep track of the number of wins by each player.

- A`player` variable keeps track of the player moves, to show which player has to make his move.

---

#### 1. Create the `empty_positions()` Function

Create the `empty_positions()` Function such that:
- The `empty_positions()` function will take `tic_tac_toe`, a two dimensional list as input, and return all the positions which are not marked.

- All the empty positions are marked with $0$.

- The `position` list will have two values for each of its elements, row and column respectively. It will collect all the rows and cloumns which are empty(marked with $0$).

- Iterates over all the positions and return the `positions` list.

---
"""

# Look out for all empty positions and return empty positions

def empty_positions(tic_tac_toe):
  # declare the position list.
    positions = []
   # use for loop to iterate over all the positions and return rows and columns of empty cells.
    for i in range(3):
        for j in range(3):
              if tic_tac_toe[i][j] == 0:
                positions.append((i, j))
    return(positions)

"""#### 2. Create the `evaluate()` Function
Create the `evaluate()` Function such that:

- The `evaluate()` function returns $1$ if player1 wins for the current position of the game after checking for all possible winning conditions.

- The `evaluate()` function returns $2$ if player2 wins for the current position of the game after checking for all possible winning conditions.

- The `evaluate()` function returns $0$ if none of the players win for the current position of the game after checking for all possible winning conditions.
"""

#Evaluate weather we have reached any conclusion or not

def evaluate(tic_tac_toe):
# check any conclusion wrt columns for player 1

# First condition is provided as a hint.
    if tic_tac_toe[0][0]==1 and tic_tac_toe[1][0]==1 and tic_tac_toe[2][0]==1:
        return 1
    elif tic_tac_toe[0][1]==1 and tic_tac_toe[1][1]==1 and tic_tac_toe[2][1]==1:
        return 1
    elif tic_tac_toe[0][2]==1 and tic_tac_toe[1][2]==1 and tic_tac_toe[2][2]==1:
        return 1

# check any conclusion wrt rows for player 1
    elif tic_tac_toe[0][0]==1 and tic_tac_toe[0][1]==1 and tic_tac_toe[0][2]==1:
        return 1
    elif tic_tac_toe[1][0]==1 and tic_tac_toe[1][1]==1 and tic_tac_toe[1][2]==1:
        return 1
    elif tic_tac_toe[2][0]==1 and tic_tac_toe[2][1]==1 and tic_tac_toe[2][2]==1:
        return 1

# check any conclusion wrt diagonals for player 1
    elif tic_tac_toe[0][0]==1 and tic_tac_toe[1][1]==1 and tic_tac_toe[2][2]==1:
        return 1
    elif tic_tac_toe[0][2]==1 and tic_tac_toe[1][1]==1 and tic_tac_toe[2][0]==1:
        return 1


# check any conclusion wrt columns for player 2

    elif tic_tac_toe[0][0]==2 and tic_tac_toe[1][0]==2 and tic_tac_toe[2][0]==2:
        return 2
    elif tic_tac_toe[0][1]==2 and tic_tac_toe[1][1]==2 and tic_tac_toe[2][1]==2:
        return 2
    elif tic_tac_toe[0][2]==2 and tic_tac_toe[1][2]==2 and tic_tac_toe[2][2]==2:
        return 2

# check any conclusion wrt rows for player 2
    elif tic_tac_toe[0][0]==2 and tic_tac_toe[0][1]==2 and tic_tac_toe[0][2]==2:
        return 2
    elif tic_tac_toe[1][0]==2 and tic_tac_toe[1][1]==2 and tic_tac_toe[1][2]==2:
        return 2
    elif tic_tac_toe[2][0]==2 and tic_tac_toe[2][1]==2 and tic_tac_toe[2][2]==2:
        return 2

# check any conclusion wrt diagonals for player 2
    elif tic_tac_toe[0][0]==2 and tic_tac_toe[1][1]==2 and tic_tac_toe[2][2]==2:
        return 2
    elif tic_tac_toe[0][2]==2 and tic_tac_toe[1][1]==2 and tic_tac_toe[2][0]==2:
        return 2


# Return 0 if no conclusions are made
    else:
        return 0

"""---

#### 3. Play with random strategy for both players.

In the following cell play Tic-Tac-Toe $100$ times and check for the number of wins for each player using the Random Algorithm. To do so follow the steps here:



1. Make two-dimensional list `tic-tac-toe` containing all zeros.

2. Check for empty positions.

3. Create a condition such that, player1 marks 1 and player2 marks 2 randomly on empty positions till either one of the player wins or all empty positions are marked and it is a draw.

4. Create another condition such that, player1 makes the first move in game one. In later games, the losing player makes the first move

5. Print the number of wins for each player at the end.
"""

#Import random Module

import random

# Play tic-tac-toe for each player with Random algorithm

# No.of wins for players
player1_wins=0
player2_wins=0
draw=0

# First player one will have the first move in the first game. Each time player wins the game another player will have the first attempt in the next game.

player=1


# We will play 100 games.

print("LET'S PLAY TIC-TAC-TOE!!")

for i in range(100):
  # tic-tac-toe Board 3*3 list
    tic_tac_toe=[[0,0,0],[0,0,0],[0,0,0]]
    print(" Start Game : ",i+1) # i starts from index 0

  # Checking for all the empty positions
    emp_positions=empty_positions(tic_tac_toe)
    print(" Start Game : ",i+1) # i starts from index 0

# while loop will run till there are no empty positions
    while(emp_positions):
         # Get move for player1
        if player==1:
        # Change in strategy than random
            if tic_tac_toe[1][1]==0 :
                playi=1
                playj=1
                print("Player 1 move:",playi,playj)


            else:
                playi,playj=random.choice(emp_positions)
                print("Player 1 move:",playi,playj)
            tic_tac_toe[playi][playj]=1
            player=2

  # Get move for player2
        elif player==2:
            playi,playj=random.choice(emp_positions)
            print("Player 2 move:",playi,playj)
            tic_tac_toe[playi][playj]=2
            player=1
# Evaluate results
        eval = evaluate(tic_tac_toe)

        if eval==1:
            print("Game Over")
            for i in range(3):
                print(tic_tac_toe[i][0],tic_tac_toe[i][1],tic_tac_toe[i][2])
            print('Player 1 wins')
            print("-----------------------------")
            player1_wins=player1_wins+1
            break

        elif eval==2:
            print("Game Over")
            for i in range(3):
                print(tic_tac_toe[i][0],tic_tac_toe[i][1],tic_tac_toe[i][2])
            print('Player 2 wins')
            print("-----------------------------")
            player2_wins=player2_wins+1
            break

# Check for empty position and return draw if no empty space is found.
        emp_positions=empty_positions(tic_tac_toe)

        if not emp_positions:
            print("Game Over")
            for i in range(3):
                print(tic_tac_toe[i][0],tic_tac_toe[i][1],tic_tac_toe[i][2])
            print('Game draw')
            print("-----------------------------")

            draw=draw+1
            break

# Print the number of wins and loses by respective players
print("Number of wins for player 1 are: ",player1_wins)
print("Number of wins for player 2 are: ",player2_wins)
print("Number of draws are:             ",draw)

"""**Q:** Repeat the above experiment few more times (run code cells) and observe the answers. What observation do you make?

**A:** One can observe that there is no significant edge of any player. Number of wins for each player is nearly the same and no particular player dominates completely.

#### 4. Play with random strategy for player2 and AI bot strategy for player1.

Now, you will have to change the strategy for `player1` as we want the bot to beat the random strategy.

In the below cell play Tic-Tac-Toe $100$ times and check for the number of wins for `player1` using AI Bot Algorithm against `player2` with Random Algorithm.

1. Make a two-dimensional list containing all zeros.

2. Check for empty positions.

3. Create a condition such that, player1 marks $1$ as per AI bot algorithm and player2 marks $2$ randomly on empty positions till either one of the player wins or all empty positions are marked and it is a draw.

4. Create another condition such that, player1 makes the first move in game one. In later games, the losing player makes the first move.

5. Print the number of wins for each player.
"""

# Here we change strategy by putting first mark at the center.
# This is implemented only for player1

player1_wins=0
player2_wins=0
draw=0
player=1

print("LET'S PLAY TIC-TAC-TOE!!")

# Play tic-tac-toe player1 with AI bot algorithm and  player2 with Random algorithm

# No.of wins for players

for i in range(100):
  # tic-tac-toe Board 3*3 list
    tic_tac_toe=[[0,0,0],[0,0,0],[0,0,0]]

  # Checking for all the empty positions
    emp_positions=empty_positions(tic_tac_toe)
    print(" Start Game : ",i+1) # i starts from index 0


  # while loop will run till there are no empty positions
    while(emp_positions):

  # Get move for player1
        if player==1:

      # Change in strategy than random
            if tic_tac_toe[1][1]==0 :
                playi=1
                playj=1
                print("Player 1 move:",playi,playj)


            else:
                playi,playj=random.choice(emp_positions)
                print("Player 1 move:",playi,playj)
            tic_tac_toe[playi][playj]=1
            player=2


    # Get move for player2
        elif player==2:
            playi,playj=random.choice(emp_positions)
            print("Player 2 move:",playi,playj)
            tic_tac_toe[playi][playj]=2
            player=1


# Evaluate results
        eval=evaluate(tic_tac_toe)

        if eval==1:
            print("Game Over")
            for i in range(3):
                print(tic_tac_toe[i][0],tic_tac_toe[i][1],tic_tac_toe[i][2])
            print('Player 1 wins')
            print("-----------------------------")
            player1_wins=player1_wins+1
            break

        elif eval==2:
            print("Game Over")
            for i in range(3):
                print(tic_tac_toe[i][0],tic_tac_toe[i][1],tic_tac_toe[i][2])
            print('Player 2 wins')
            print("-----------------------------")

            player2_wins=player2_wins+1
            break

    # Check for empty position and return draw if no empty space is found.
        emp_positions=empty_positions(tic_tac_toe)

        if not emp_positions:
            print("Game Over")
            for i in range(3):
                print(tic_tac_toe[i][0],tic_tac_toe[i][1],tic_tac_toe[i][2])
            print('Game draw')
            print("-----------------------------")

            draw=draw+1
            break

# Print the number of wins and loses by respective players
# Driver Code
print("Number of wins for player 1 are: ",player1_wins)
print("Number of wins for player 2 are: ",player2_wins)
print("Number of draws are            : ",draw)

"""**Q:** Repeat the above experiment few more times (run code cells) and share your observations/findings?

**A:**  One can observe that there is a significant edge for the `player1`. The number of wins for the `player1` is more compared  to the `player2`. Hence, our AI bot is performing better than a random strategy.

---

### How To Submit The Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_CapstoneProject1**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_CapstoneProject1** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""